import Link from 'next/link'
import { registry, getComponents } from '@/lib/registry'

export default function HomePage() {
  const components = getComponents()

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="max-w-3xl mx-auto px-4 py-8 md:py-12 space-y-8">
        {/* Registry Header */}
        <div className="space-y-4">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-lg bg-accent border border-border flex items-center justify-center text-xl font-bold text-foreground">
              {registry.name.charAt(0).toUpperCase()}
            </div>
            <div className="flex-1 min-w-0">
              <h1 className="text-xl font-bold text-foreground">
                {registry.name}
              </h1>
              <p className="text-sm text-muted-foreground mt-0.5">
                Component Registry
              </p>
            </div>
          </div>

          {/* Links & Stats */}
          <div className="flex flex-wrap items-center gap-3">
            {registry.homepage && (
              <a
                href={registry.homepage}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg>
                Website
              </a>
            )}
            <span className="text-xs text-muted-foreground">
              {components.length} components
            </span>
          </div>
        </div>

        {/* Components List */}
        <div className="space-y-4">
          <h2 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
            Components
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {components.map((item) => (
              <Link
                key={item.name}
                href={`/docs/${item.name}`}
                className="flex items-start gap-3 px-4 py-3 rounded-lg border border-border hover:bg-accent transition-all group"
              >
                <div className="min-w-0 flex-1">
                  <div className="text-sm font-medium text-foreground group-hover:text-foreground">
                    {item.title || item.name}
                  </div>
                  {item.description && (
                    <p className="text-xs text-muted-foreground mt-0.5 line-clamp-2 leading-relaxed">
                      {item.description}
                    </p>
                  )}
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-muted-foreground mt-0.5 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity"><path d="m9 18 6-6-6-6"/></svg>
              </Link>
            ))}
          </div>
        </div>
      </div>

      {/* Status Bar */}
      <div className="border-t border-border bg-background px-4 py-2 text-xs text-muted-foreground flex items-center justify-between">
        <span>{components.length} components</span>
        <span>Generated by shadocs</span>
      </div>
    </div>
  )
}
