import Link from 'next/link'
import { registry, getBlocks, formatBlockName } from '@/lib/registry'
import { BlockGrid } from '@/components/block-grid'
import { ModeToggle } from '@/components/mode-toggle'

export default function HomePage() {
  const blocks = getBlocks()

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="border-b border-border bg-background/95 backdrop-blur sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-md bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold">
              {registry.name.charAt(0).toUpperCase()}
            </div>
            <span className="text-sm font-semibold">{registry.name}</span>
            <span className="text-xs text-muted-foreground px-1.5 py-0.5 rounded bg-muted">Blocks</span>
          </div>
          <div className="flex items-center gap-3">
            {registry.homepage && (
              <a
                href={registry.homepage}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs text-muted-foreground hover:text-foreground transition-colors"
              >
                Website
              </a>
            )}
            <span className="text-xs text-muted-foreground">{blocks.length} blocks</span>
            <ModeToggle />
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="border-b border-border bg-muted/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12 md:py-16">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight">{registry.name}</h1>
          <p className="text-lg text-muted-foreground mt-2 max-w-2xl">
            Ready-to-use blocks built with shadcn/ui. Copy and paste into your apps.
          </p>
          <div className="mt-4 flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2 font-mono text-xs w-fit">
            <span className="text-muted-foreground select-none">$</span>
            <code>npx shadcn@latest add {registry.homepage}/r/[block-name].json</code>
          </div>
        </div>
      </section>

      {/* Blocks Grid */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
              All Blocks
            </h2>
          </div>

          <BlockGrid blocks={blocks.map((b) => ({
            name: b.name,
            title: b.title || formatBlockName(b.name),
            description: b.description,
            fileCount: b.files?.length || 0,
          }))} />
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border bg-background px-4 py-4 text-center text-xs text-muted-foreground">
        Generated by shadocs
      </footer>
    </div>
  )
}
