"use client"
// This file is auto-generated by the shadocs CLI during build/dev.
// It maps block names to dynamically imported React components.

export const blockComponents: Record<string, React.ComponentType> = {}
