// This file is auto-generated by the shadocs CLI during build/dev.
// It maps example names to dynamically imported React components.
// The placeholder below is replaced when `shadocs dev` or `shadocs build` runs.

export const exampleComponents: Record<string, React.ComponentType> = {}
